First commit (with bugs)
lapkina/Sprint_4 pull request #1
Opened 2022-10-09 19:54 UTC by lapkina

2022-10-10 14:31 UTC, pavel-ulan requested changes
Начало положено, это уже неплохо.
У тебя нет тестов на блок вопросов, доделай (и исправь текущие 2). Надо так же почистить код от закоменченных строк и в целом провести рефакторинг стиля, т.к. сейчас очень много непонятного оформления.
Ну и почитай, что коммитят в репозиторий, а что нет. Можешь это проследить по тому, какие файлы заносят в .gitignore обычно (можешь поискать шаблоны файлов, в интернете много примеров под каждый из типов проектов. Например вот https://github.com/github/gitignore). Так например папку .idea и файлы iml в реп не коммитят.

2022-10-10 14:31 UTC, pavel-ulan commented on src/main/java/ru/yandex/praktikum/Samokat/PO/MainPage.java
> +    //((JavascriptExecutor)driver).executeScript ("arguments[0].scrollIntoView();",element);
Если что-то попробовала и поняла, что тебе это не надо, не забывай удалять. увидеть закомментированный кусок кода в проекте последнее чего хотелось бы.

2022-10-10 14:31 UTC, pavel-ulan commented on src/test/java/ru/yandex/praktikum/Samokat/TestsOrder.java
> +
Странное оформление. Много пустых строк, пропусков и т.п. как правило, так не делают. Есть определенные требования, они иногда немного отличаются, но в целом схожи (так называемые кодСтайлГайды). Непросто сходу придерживаться всех правил, но базовые стоит поискать и почитать. Есть плагины codeStyleCheckers которые можно в IDEA подключить и которые будут подсвечивать ошибки. ну и иногда стоит использовать стандартные фишки IDEA типа rerange code или optimize imports (доступные так же в виде хотКеев).

2022-10-10 14:31 UTC, pavel-ulan commented on src/test/java/ru/yandex/praktikum/Samokat/TestsAccordion.java
> +    }
Даже если не смотреть на то, что у тебя только 2 вопроса разбирается.... где сама проверка?
ты кликнула на вопрос и вытянула текст ответа, проверки нет. тест подразумевает, что что-то должно проверяться, на то он и тест. это не сценарий действий.

2022-10-10 14:31 UTC, pavel-ulan commented on src/test/java/ru/yandex/praktikum/Samokat/TestsAccordion.java
> +    }
Ну и возвращаясь к вопросам. В задании говорится про все вопросы, т.е. тестов должно быть столько же как и вопросов, что бы каждый проверялся отдельно. Доделай их пожалуйста.

2022-10-16 17:39 UTC, lapkina commented on src/test/java/ru/yandex/praktikum/Samokat/TestsOrder.java
> +
нас не учили следовать стайлгайдам и по-моему, сейчас это не самое главное, ведь фокус - в том, что писать и как. кажется, отступы  можно будет наверстать позже.

2022-10-16 19:53 UTC, pavel-ulan requested changes
Почти хорошо. Надо вынести конфигурацию драйвера, что бы она не фигурировала в теле теста (тесты для проверки, все остальное должно быть вне метода. В Before, в родительском классе или как-то иначе, но точно не в тестовом методе).

2022-10-16 19:53 UTC, pavel-ulan commented on src/test/java/ru/yandex/praktikum/Samokat/TestsAccordion.java
> +        //WebDriver driver = new ChromeDriver();
Стоило не комментить эту строку, а удалить ее. В финальном виде работы не должно быть неинформативных комментов.

2022-10-16 19:53 UTC, pavel-ulan commented on src/test/java/ru/yandex/praktikum/Samokat/TestsAccordion.java
> +        driver = new ChromeDriver( options );
Все это настройки. Настройки не должны фигурировать в теле теста. Тест, это проверка чего-то, все настройки должны происходить до этого. Как вариант в Before блоке.

2022-10-16 19:53 UTC, pavel-ulan commented on src/test/java/ru/yandex/praktikum/Samokat/TestsAccordion.java
> +        driver = new ChromeDriver( options );
Это надо исправить.

2022-10-16 19:53 UTC, pavel-ulan commented on src/test/java/ru/yandex/praktikum/Samokat/TestsOrder.java
> +
С одной стороны - да, с другой чем раньше начнешь им следовать, тем проще будет потом, т.к. следовать этим гайдам всеравно придется.

2022-10-22 14:12 UTC, pavel-ulan approved these changes
Оке, все хорошо =)

2022-12-11 13:40 UTC, merged